export default {
  THEME_CHANGE: 'THEME_CHANGE',
  THEME_INIT: 'THEME_INIT',

  POPULAR_REFRESH: 'POPULAR_REFRESH', //最热加载模块
  POPULAR_REFRESH_SUCCESS: 'POPULAR_REFRESH_SUCCESS', //最热加载成功
  POPULAR_REFRESH_FAIL: 'POPULAR_REFRESH_FAIL',// 最热加载失败
  POPULAR_LOAD_MORE_SUCCESS: 'POPULAR_LOAD_MORE_SUCCESS',// 上拉加载更多
  POPULAR_LOAD_MORE_FAIL: 'POPULAR_LOAD_MORE_FAIL', //上拉加载更多失败
  
  TRENDING_REFRESH: 'TRENDING_REFRESH', // 趋势加载
  TRENDING_REFRESH_SUCCESS: 'TRENDING_REFRESH_SUCCESS',// 趋势加载成功
  TRENDING_REFRESH_FAIL: 'TRENDING_REFRESH_FAIL', // 趋势加载失败
  TRENDING_LOAD_MORE_SUCCESS: 'TRENDING_LOAD_MORE_SUCCESS', // 趋势上啦更多成功
  TRENDING_LOAD_MORE_FAIL: 'TRENDING_LOAD_MORE_FAIL', // 趋势上啦更多失败

  FAVORITE_REFRESH_SUCCESS: 'FAVORITE_REFRESH_SUCCESS', // 收藏成功
  FAVORITE_REFRESH: 'FAVORITE_REFRESH', // 刷新收藏
  FAVORITE_REFRESH_FAIL: 'FAVORITE_REFRESH_FAIL', // 收藏失败

  SET_TOKEN: 'SET_TOKEN', // token
  KEY_BOADRDING_PASS: 'KEY_BOADRDING_PASS', // token
  CLICK_POUPULAR_FAVORITE: 'CLICK_POUPULAR_FAVORITE', // 最热点击收藏更新列表
  CLICK_TRENDING_FAVORITE: 'CLICK_TRENDING_FAVORITE' , // 趋势点击收藏更新列表

  KEYSANDLANG_SUCCESS: 'KEYSANDLANG_SUCCESS'

}
